name: Github workflow
on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
   
